server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userpostproject
    username: root
    password: Eziomanish@1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

